"use client";
import { useState } from "react";
import { CheckIcon, ShieldIcon } from "./icons";
type Brief = { summary: string; designedToDo: string[]; maySuit: string[]; tradeoffsAndRisks: string[]; questionsBeforeActivation: string[]; dataBasis: Array<{ point: string; basis: "BLOCview demo data" | "Verified 8004scan data" }> };
export function AgentBrief({ slug }: { slug: string }) {
  const [brief, setBrief] = useState<Brief | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function generate() { setLoading(true); setError(""); try { const response = await fetch("/api/agent-brief", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug }) }); const result = await response.json() as { brief?: Brief; error?: string; retryAfterSeconds?: number }; if (!response.ok || !result.brief) throw new Error(result.retryAfterSeconds ? `${result.error} Try again in ${result.retryAfterSeconds}s.` : result.error ?? "Unable to generate a brief."); setBrief(result.brief); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to generate a brief."); } finally { setLoading(false); } }
  return <section className="agent-brief"><div className="brief-intro"><div><span className="eyebrow">OpenAI-powered explanation</span><h2>AI Agent Brief</h2><p>Turn the information shown on this profile into a concise, plain-English review.</p></div><button className="primary-button brief-button" onClick={generate} disabled={loading}>{loading ? <><i className="brief-spinner" />Generating brief…</> : brief ? "Generate again" : "Generate AI Agent Brief"}</button></div><div className="brief-safety"><ShieldIcon /><span>AI-generated explanation — not financial advice.</span><small>This brief does not activate the agent or move funds.</small></div>{error && <p className="brief-error" role="alert">{error}</p>}{brief && <div className="brief-result" aria-live="polite"><p className="brief-summary">{brief.summary}</p><div className="brief-grid"><BriefList title="Designed to do" items={brief.designedToDo} /><BriefList title="May suit" items={brief.maySuit} /><BriefList title="Trade-offs and risks" items={brief.tradeoffsAndRisks} /><BriefList title="Questions before activation" items={brief.questionsBeforeActivation} /></div><div className="basis-list"><h3>Data basis</h3>{brief.dataBasis.map((item, index) => <div key={`${item.point}-${index}`}><CheckIcon /><span>{item.point}</span><strong className={item.basis === "Verified 8004scan data" ? "basis-verified" : "basis-demo"}>{item.basis}</strong></div>)}</div></div>}</section>;
}
function BriefList({ title, items }: { title: string; items: string[] }) { return <article><h3>{title}</h3><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></article>; }
