"use client";
import { useRef, useState } from "react";
import type { RangePilotLiveAgent } from "@/lib/range-pilot-watch-agents";
type Task = Record<string, unknown> & { taskId: string; status: "accepted" | "running" | "completed" | "failed"; input?: unknown; createdAt?: string; startedAt?: string; completedAt?: string };
const inputs: Record<number, Record<string, unknown>> = { 321941: { tokenId: "42" }, 321995: { poolId: "WBNB-USDT-500", boundaries: [-100, 0, 100] }, 322046: { assetId: "usd-stablecoins", markets: ["core-vUSDC", "core-vUSDT"] }, 322090: { accountAddress: "0x1111111111111111111111111111111111111111", warningRatio: "1.25" } };
export function HireAgent({ agent }: { agent: RangePilotLiveAgent }) {
  const [review, setReview] = useState(false), [busy, setBusy] = useState(false), [task, setTask] = useState<Task | null>(null), [error, setError] = useState(""); const key = useRef(""); const input = inputs[agent.tokenId];
  async function refresh(id: string) { try { const r = await fetch(`/api/range-pilot-watch/tasks/${id}`, { cache: "no-store" }), b = await r.json(); if (!r.ok) throw new Error(); setTask(b); return b as Task; } catch { setError("Task status is temporarily unavailable. Try refresh again."); return null; } }
  async function start() { if (busy) return; setBusy(true); setError(""); if (!key.current) key.current = crypto.randomUUID(); try { const r = await fetch(`/api/range-pilot-watch/agents/${agent.tokenId}/tasks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input, idempotencyKey: key.current }) }), b = await r.json(); if (!r.ok) throw new Error(b.error); setTask(b); let current = b as Task; for (let n = 0; n < 8 && !["completed", "failed"].includes(current.status); n++) { await new Promise((done) => setTimeout(done, 2000)); current = await refresh(current.taskId) ?? current; } } catch (e) { setError(e instanceof Error ? e.message : "Task service is temporarily unavailable. No task was started."); } finally { setBusy(false); } }
  return <section className="assessment-handoff hire-agent" aria-labelledby="hire-title"><header><span className="eyebrow">Verified hiring interface</span><h2 id="hire-title">Hire agent</h2><p>Start a one-time read-only task with this agent. BLOCview verified the callable task interface and lifecycle—not security, performance, profitability, or suitability.</p></header>
    {!review && !task && <button className="primary-button" onClick={() => setReview(true)}>Hire Agent</button>}
    {review && !task && <div className="hire-review"><h3>Review task</h3><dl><div><dt>Agent</dt><dd>{agent.name}</dd></div><div><dt>Strategy</dt><dd>{agent.category}</dd></div><div><dt>Operation</dt><dd>Read-only assessment</dd></div><div><dt>Input</dt><dd><code>{JSON.stringify(input)}</code></dd></div><div><dt>Evidence destination</dt><dd>Durable engagement receipt</dd></div><div><dt>Authority</dt><dd>No wallet or transaction authority</dd></div><div><dt>Payment</dt><dd>Not required</dd></div></dl><p>No wallet connection, signature, transaction, payment, custody, or authority over funds.</p><button className="primary-button" disabled={busy} onClick={start}>{busy ? "Starting task…" : "Start task"}</button></div>}
    {error && <div className="assessment-result error" role="alert"><strong>{error}</strong>{task && <button className="secondary-button" onClick={() => refresh(task.taskId)}>Refresh status</button>}</div>}
    {task && <div className={`assessment-result ${task.status === "failed" ? "error" : "complete"}`}><strong>{["completed", "failed"].includes(task.status) ? "Engagement Receipt" : "Task accepted"}</strong><dl className="hire-receipt"><div><dt>Task ID</dt><dd>{task.taskId}</dd></div><div><dt>Agent</dt><dd>{agent.name} · ERC-8004 #{agent.tokenId}</dd></div><div><dt>Strategy</dt><dd>{agent.category}</dd></div><div><dt>Operation</dt><dd>Read-only assessment</dd></div><div><dt>Input</dt><dd><code>{task.input === undefined ? "Not recorded" : JSON.stringify(task.input)}</code></dd></div><div><dt>Status</dt><dd>{task.status}</dd></div><div><dt>Outcome</dt><dd>{String(task.outcomeStatus ?? "Pending")}</dd></div><div><dt>Created</dt><dd>{task.createdAt ?? "Not recorded"}</dd></div><div><dt>Started</dt><dd>{task.startedAt ?? "Not recorded"}</dd></div><div><dt>{task.status === "failed" ? "Failed" : "Completed"}</dt><dd>{task.completedAt ?? "Not recorded"}</dd></div><div><dt>Payment</dt><dd>Not required</dd></div><div><dt>Authority</dt><dd>Read only</dd></div></dl>{task.result !== undefined && <pre>{JSON.stringify(task.result, null, 2)}</pre>}<button className="secondary-button" onClick={() => refresh(task.taskId)}>Refresh status</button></div>}
  </section>;
}
