import { isAssessmentTokenId, validateAssessmentRequest, type AssessmentTokenId } from "./range-pilot-assessments.ts";
export const RANGE_PILOT_TASK_ORIGIN = "https://range-pilot-watch.onrender.com";
export const TASK_SLUGS: Record<AssessmentTokenId, string> = { 321941: "range-rebalance", 321995: "grid-band", 322046: "venus-yield", 322090: "venus-borrow-buffer" };
export const TERMINAL_TASK_STATUSES = new Set(["completed", "failed"]);
const KEY = /^[A-Za-z0-9._:-]{8,128}$/;
export function validateHireRequest(tokenId: number, value: unknown) { if (!isAssessmentTokenId(tokenId) || !value || typeof value !== "object" || Array.isArray(value)) return null; const body = value as Record<string, unknown>; if (Object.keys(body).some((key) => !["input", "idempotencyKey"].includes(key)) || typeof body.idempotencyKey !== "string" || !KEY.test(body.idempotencyKey)) return null; const input = validateAssessmentRequest(tokenId, body.input); return input ? { operation: "read-only-assessment", input, idempotencyKey: body.idempotencyKey } : null; }
export function validTaskId(value: string) { return /^tsk_[A-Za-z0-9_-]{16,128}$/.test(value); }
export function sanitizeTask(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const v = value as Record<string, unknown>; if (typeof v.taskId !== "string" || !validTaskId(v.taskId) || typeof v.status !== "string" || !["accepted", "running", "completed", "failed"].includes(v.status)) return null; const allowed = ["taskId", "agentId", "agentSlug", "operation", "input", "status", "outcomeStatus", "createdAt", "startedAt", "completedAt", "expiresAt", "events", "result", "failure"]; return Object.fromEntries(allowed.filter((key) => v[key] !== undefined).map((key) => [key, v[key]])); }
export function taskError(status: number) { if (status === 409) return { error: "This confirmation conflicts with an earlier task request. Review the input and start a new confirmation." }; if (status === 404) return { error: "That task could not be found." }; if (status === 400) return { error: "The task input is invalid." }; return { error: "Task service is temporarily unavailable. No task was started." }; }
